### ISSUE TITLE
Minting on Remix

### ISSUE THREAD

**Issue by vanshiqa** [paulrberg/contracts#15]
To reproduce:
On Remix - deploy GodModeErc20 code at address -  0x5eD8BD53B0c3fa3dEaBd345430B1A3a6A4e8BD7C.

Mint at Metamask address,  mintAmt = 1 

Error: 
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
execution reverted

**Comment by paulrberg** [comment]
Hi @vanshiqa! There's a lot of reasons why this happened to you. I recommend posting this sort of question on [StackExchange](https://ethereum.stackexchange.com/), where you have better odds of finding someone who knows the answer.

Double-check that you're connected to the correct network.
