### ISSUE TITLE
Update PERMIT_TYPEHASH to more commonly adopted permit typehash

### ISSUE THREAD

**Issue by surbhiaudichya** [paulrberg/contracts#23]
Let's consider changing the `PERMIT_TYPEHASH` in `Erc20Permit.sol` to the more commonly adopted hash: 

```solidity
keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)");
```

The benefit of doing this would be that future contracts inheriting from `Erc20Permit` would be compatible with the commonly used frontend library [eth-permit](https://github.com/dmihal/eth-permit) to create valid signatures.

**Comment by paulrberg** [comment]
#24 has been merged.
