### ISSUE TITLE
Erc20 mintInternal function doesn’t emit Transfer Event 

### ISSUE THREAD

**Issue by surbhiaudichya** [paulrberg/contracts#8]
Opening an issue to discuss why ERC20 implementation doesn't emit a "Transfer" event when minting new tokens?

**Comment by paulrberg** [comment]
The reason may have been optionality. There are users who may prefer not to emit a "Transfer" event on minting new tokens, although now I concede that I don't see many use cases in which this would be desiraeable.

As you found out, Etherscan doesn't show mints that don't emit a "Transfer" event.

**Comment by paulrberg** [comment]
Replaced {Mint,Burn} with {Transfer} events. Thanks for reporting this, Surbhi!

[d4d1250](https://github.com/paulrberg/contracts/commit/d4d12504e7190e0f1c25cbba1dbc8b7b3fbeb225)
